export default [
  {
    id: 1,
    name: 'プラチナアーマー',
    icon: 'icons-frame-platinum',
    exp: 1000,
    rarity: 5,
    standalone: false,
    restricted: false,
  },
  {
    id: 2,
    name: 'ブラックアーマー',
    icon: 'icons-frame-black',
    exp: 5000,
    rarity: 7,
    standalone: false,
    restricted: false,
  },
  {
    id: 9,
    name: 'アムール',
    icon: 'icons-frame-silver',
    exp: 4000,
    rarity: 3,
    standalone: true,
    restricted: true,
  },
  {
    id: 5,
    name: 'アレグリア',
    icon: 'icons-frame-gold',
    exp: 18000,
    rarity: 4,
    standalone: true,
    restricted: true,
  },
  {
    id: 6,
    name: 'フロイデ',
    icon: 'icons-frame-platinum',
    exp: 19000,
    rarity: 5,
    standalone: true,
    restricted: true,
  },
  {
    id: 4,
    name: 'リーベ',
    icon: 'icons-frame-sapphire',
    exp: 19000,
    rarity: 6,
    standalone: true,
    restricted: true,
  },
  {
    id: 7,
    name: 'ファラハ',
    icon: 'icons-frame-black',
    exp: 20000,
    rarity: 7,
    standalone: true,
    restricted: true,
  },
  {
    id: 3,
    name: 'ハッピー',
    icon: 'icons-frame-black',
    exp: 150000,
    rarity: 7,
    standalone: true,
    restricted: false,
  },
  {
    id: 8,
    name: '千狐',
    icon: 'icons-frame-black',
    exp: 10005,
    rarity: 7,
    standalone: false,
    restricted: false,
  },
]
